package modelo;
// Generated 08-mar-2021 14:06:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {

//haremos las consultas sobre las clases, no sobre las tablas, si nos fijamos, tenemos aqui las columnas con su tipo equivalente en Java. Tenemos las clases mapeadas
    //Es un Javabin cumle las 3 condiciones
     private int idCategoria;
     private String nombreCategoria; 
     private double complementoCategoria;
     private double salarioBaseCategoria;
     private Set trabajadorbbdds = new HashSet(0); //Representa la FK, utilizando el tipo conjunto para los trabajadores

    public Categorias() {
    }

	
    public Categorias(int idCategoria, String nombreCategoria, double complementoCategoria, double salarioBaseCategoria) {
        this.idCategoria = idCategoria;
        this.nombreCategoria = nombreCategoria;
        this.complementoCategoria = complementoCategoria;
        this.salarioBaseCategoria = salarioBaseCategoria;
    }
    public Categorias(int idCategoria, String nombreCategoria, double complementoCategoria, double salarioBaseCategoria, Set trabajadorbbdds) {
       this.idCategoria = idCategoria;
       this.nombreCategoria = nombreCategoria;
       this.complementoCategoria = complementoCategoria;
       this.salarioBaseCategoria = salarioBaseCategoria;
       this.trabajadorbbdds = trabajadorbbdds;
    }
   
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public double getComplementoCategoria() {
        return this.complementoCategoria;
    }
    
    public void setComplementoCategoria(double complementoCategoria) {
        this.complementoCategoria = complementoCategoria;
    }
    public double getSalarioBaseCategoria() {
        return this.salarioBaseCategoria;
    }
    
    public void setSalarioBaseCategoria(double salarioBaseCategoria) {
        this.salarioBaseCategoria = salarioBaseCategoria;
    }
    public Set getTrabajadorbbdds() {
        return this.trabajadorbbdds;
    }
    
    public void setTrabajadorbbdds(Set trabajadorbbdds) {
        this.trabajadorbbdds = trabajadorbbdds;
    }




}


